# Generated by Django 2.2.4 on 2020-04-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.AddField(
            model_name='transaction',
            name='charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.Charge'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
