# Generated by Django 2.2.4 on 2019-12-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
