# Generated by Django 2.2.4 on 2019-12-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191213_0107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
